import {
  BadgeCheck,
  BanknoteArrowDown,
  BanknoteArrowUp,
  BarChart3,
  ClipboardCheck,
  CreditCard,
  FileStack,
  FileText,
  Gavel,
  LayoutDashboard,
  ReceiptText,
  Scale,
  ScrollText,
  ShieldCheck,
  Wallet,
  Wallet2,
  type LucideIcon,
} from "lucide-react";

/** Domain-id -> icon. Keyed by `DomainDescriptor.id` (see registry.ts). */
export const DOMAIN_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  cod: BanknoteArrowDown,
  "cash-handovers": Wallet2,
  "cash-sessions": Wallet,
  "cash-variances": Scale,
  reconciliations: ClipboardCheck,
  obligations: ScrollText,
  fees: ReceiptText,
  documents: FileText,
  adjustments: FileStack,
  disputes: Gavel,
  payouts: BanknoteArrowUp,
  approvals: BadgeCheck,
  "payment-methods": CreditCard,
  reports: BarChart3,
  audit: ShieldCheck,
};
